project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: https://mekanavsharma.github.io/Blog/
  #body-header: subscribe.html
  description: "Sample blog"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/mekanavsharma
      - icon: twitter
        href: https://twitter.com/kanav608
      - icon: linkedin
        href: https://www.linkedin.com/in/kanav-sharma-896b1021b/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

