# .github/workflows/deploy.yml
name: Deploy Quarto Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Clear Quarto Cache
      run: rm -rf ~/.cache/quarto
      
    # Add any other steps required for setup/installation
    
    - name: Build Quarto Site
      run: quarto render
      
    # Steps to deploy the built site